### ISSUE TITLE
Mouseover Initiation with Expanding Push Units

### ISSUE THREAD

**Issue by ADeanKelly** [Adcase/adcase.js#1]
Hi Guille,

Can you add Mouseover initiation as an Expand Action to the current Push Unit #101.

Most Agencies are happy with the Click to Expand, but some are more interested in the Mouseover initiation for user engagement.

Thanks,
Dean

**Comment by gfilipich** [comment]
Done: https://builder.adcase.io/builder/push

Please let me know if it works for you

Thank you
